apiVersion: gateway.networking.k8s.io/v1beta1  # Define a versão da API usada para este recurso do Kubernetes.
kind: Gateway  # Especifica que estamos criando um "Gateway", que gerencia o tráfego de entrada na aplicação.

metadata:  # Metadados do Gateway, como nome e identificadores.
  name: fatec-gateway  # Nome do Gateway, usado para identificá-lo dentro do cluster.

spec:  # Especificações do Gateway.
  gatewayClassName: nginx  # Define a classe do Gateway, que determina qual controlador gerenciará este Gateway.
  
  listeners:  # Lista de ouvintes (listeners) que definem como o tráfego será recebido.
    - name: http  # Nome do ouvinte (listener) para referência interna.
      protocol: HTTP  # Define o protocolo utilizado (HTTP, neste caso).
      port: 80  # Porta em que o Gateway aceitará conexões.

      allowedRoutes:  # Define quais namespaces podem criar rotas associadas a este Gateway.
        namespaces:
          from: All  # Permite que rotas de qualquer namespace sejam associadas a este Gateway.
