---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1  # Número de réplicas da aplicação
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: vue-frontend
        image: ricardostudo/fatec-frontend:v8.0  # Substitua com o nome correto da imagem (Docker Hub ou registro privado)
        ports:
        - containerPort: 8080  # Porta em que a aplicação Vue.js está rodando
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Porta externa exposta
      targetPort: 8080  # Porta onde o container Vue.js está escutando
