---
apiVersion: apps/v1
kind: Deployment  # Define o tipo de recurso como um Deployment
metadata:
  name: backend-omdb  # Nome do Deployment
  namespace: production  # Namespace onde o recurso será criado
  labels:
    app: backend-omdb  # Rótulos para identificar e organizar recursos
spec:
  replicas: 1  # Número de réplicas da aplicação
  selector:
    matchLabels:
      app: backend-omdb  # Filtro para selecionar pods com a label 'app: backend-omdb'
  template:
    metadata:
      labels:
        app: backend-omdb  # Rótulos usados para identificar os pods
    spec:
      containers:
      - name: backend-omdb  # Nome do container
        image: ricardostudo/fatec-backend-omdb:latest  # Substitua com o nome correto da imagem (Docker Hub ou registro privado)
        ports:
        - containerPort: 8000  # Porta em que a aplicação backend omdb estará rodando


      