# Default values for backend-omdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  image_name: us-east1-docker.pkg.dev/mythic-attic-450700-r8/backend-omdb/fatec-backend-omdb:latest

nameOverride: ""
fullnameOverride: ""

Deployment:
  namespace: production
  replicas: 1
  containerPort: 8000

ServiceKind:
  enabled: false
  port: 8000  # Porta interna do serviço
  nodePort: 30000
  targetPort: 8000
  type: NodePort

ServiceGateway:
  enabled: true
  port: 80  # Porta interna do serviço
  targetPort: 8000
  protocol: TCP



