---
apiVersion: apps/v1
kind: Deployment  # Define o tipo de recurso como um Deployment
metadata:
  name: backend-poke  # Nome do Deployment
  namespace: production  # Namespace onde o recurso será criado
  labels:
    app: backend-poke  # Rótulos para identificar e organizar recursos
spec:
  replicas: 1  # Número de réplicas da aplicação
  selector:
    matchLabels:
      app: backend-poke  # Filtro para selecionar pods com a label 'app: backend-poke'
  template:
    metadata:
      labels:
        app: backend-poke  # Rótulos usados para identificar os pods
    spec:
      containers:
      - name: backend-poke  # Nome do container
        image: ricardostudo/fatec-backend-poke:latest  # Substitua com o nome correto da imagem (Docker Hub ou registro privado)
        ports:
        - containerPort: 8001  # Porta em que a aplicação backend pokemon estará rodando

