# Default values for backend-omdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

Deployment:
  namespace: production
  replicas: 1
  containerPort: 8001

ServiceKind:
  enabled: false
  port: 8001  # Porta interna do serviço
  nodePort: 30001
  targetPort: 8001
  type: NodePort

ServiceGateway:
  enabled: true
  port: 80  # Porta interna do serviço
  targetPort: 8001
  protocol: TCP



