---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-poke
  namespace: production
  labels:
    app: backend-poke
spec:
  replicas: 1  # Número de réplicas da aplicação
  selector:
    matchLabels:
      app: backend-poke
  template:
    metadata:
      labels:
        app: backend-poke
    spec:
      containers:
      - name: backend-poke
        image: ricardostudo/fatec-backend-poke:latest  # Substitua com o nome correto da imagem (Docker Hub ou registro privado)
        ports:
        - containerPort: 8001  # Porta em que a aplicação backend pokemon estara rodando
  
---
apiVersion: v1
kind: Service
metadata:
  name: backend-poke-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: backend-poke
  ports:
    - protocol: TCP
      port: 8001  # Porta externa exposta
      targetPort: 8001  # 
      nodePort: 30002  # 
