---
apiVersion: apps/v1
kind: Deployment  # Define o tipo de recurso como um Deployment
metadata:
  name: backend-poke  # Nome do Deployment
  namespace: production  # Namespace onde o recurso será criado
  labels:
    app: backend-poke  # Rótulos para identificar e organizar recursos
spec:
  replicas: 1  # Número de réplicas da aplicação
  selector:
    matchLabels:
      app: backend-poke  # Filtro para selecionar pods com a label 'app: backend-poke'
  template:
    metadata:
      labels:
        app: backend-poke  # Rótulos usados para identificar os pods
    spec:
      containers:
      - name: backend-poke  # Nome do container
        image: ricardostudo/fatec-backend-poke:latest  # Substitua com o nome correto da imagem (Docker Hub ou registro privado)
        ports:
        - containerPort: 8001  # Porta em que a aplicação backend pokemon estará rodando
---
apiVersion: v1
kind: Service  # Define o tipo de recurso como Service
metadata:
  name: backend-poke-service  # Nome do serviço
  namespace: production  # Namespace onde o serviço será criado
spec:
  type: NodePort  # Tipo de serviço que expõe a aplicação com um NodePort
  selector:
    app: backend-poke  # Seleciona os pods que têm a label 'app: backend-poke'
  ports:
    - port: 8001  # Porta interna do serviço
      targetPort: 8001  # Porta no pod que será mapeada
      nodePort: 30001  # Porta exposta no nó (externa)
