---
apiVersion: v1
kind: Service  # Define o tipo de recurso como Service
metadata:
  name: vue-frontend-service  # Nome do serviço
  namespace: frontend  # Namespace onde o serviço será criado
spec:
  type: NodePort  # Tipo de serviço que expõe a aplicação com um NodePort
  selector:
    app: frontend  # Seleciona os pods que têm a label 'app: frontend'
  ports:
    - port: 80  # Porta interna do serviço (padrão HTTP)
      targetPort: 8080  # Porta no pod que será mapeada
      nodePort: 30002  # Porta exposta no nó (externa)