name: Build and Deploy backend_omdb app

# Teste Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Build-and-deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug: Verificar estrutura do workspace
      - name: Debug workspace
        run: |
          ls -la
          pwd

      # Instalar kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Configurar kubectl for kind
      - name: Configure kubectl
        run: |
          kubectl config set-context kind-fatec-cluster --cluster=kind-fatec-cluster --user=kind-fatec-cluster

      # Verifica conexão kubernetes
      - name: Check connection with Kubernetes
        run: |
          kubectl get pods -A
          kubectl get nodes

      # Instalar Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      # Realizar login no Docker registry 
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # acessa a pasta backend_omdd, gerar uma imagem com o Dockerfile e armazenar em um registry
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backend_omdb
      #     file: backend_omdb/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_REGISTRY }}/backend_omdb:latest

      # # Deploy Backend OMDB com Helm
      # - name: Deploy Backend OMDB with Helm
      #   run: |
      #     cd backend_omdb/kubernetes
      #     ls
      #     pwd
      #     helm upgrade --install backend-omdb . --values values.yaml
      
      # # Deploy Backend POKE com Helm
      # - name: Deploy Backend POKE with Helm
      #   run: |
      #     cd backend_pokemon/kubernetes
      #     ls
      #     pwd
      #     helm upgrade --install backend-pokemon . --values values.yaml
      
      # Deploy Frontend com Helm
      - name: Deploy Frontend with Helm
        run: |
          cd front-end/kubernetes
          ls
          pwd
          helm upgrade --install frontend . --values values.yaml
          