name: CI/CD - Build and Deploy backend_omdb & backend_pokemon

# Disparo manual ativado, eventos automáticos desativados
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          ls -la
          pwd

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend_omdb Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend_omdb
          file: backend_omdb/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/fatec-backend-omdb:latest

      - name: Build and push backend_pokemon Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend_pokemon
          file: backend_pokemon/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/fatec-backend-poke:latest

  deploy:
    name: Deploy to Kubernetes
    needs: build  # Só executa após o build
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          kubectl config set-context kind-fatec-cluster --cluster=kind-fatec-cluster --user=kind-fatec-cluster

      - name: Check connection with Kubernetes
        run: |
          kubectl get pods -A
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Deploy Backend OMDB with Helm
        run: |
          cd backend_omdb/kubernetes
          helm upgrade --install backend-omdb . --values values.yaml

      - name: Deploy Backend POKE with Helm
        run: |
          cd backend_pokemon/kubernetes
          helm upgrade --install backend-pokemon . --values values.yaml
