name: CI/CD - Build and Deploy Frontend

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          ls -la
          pwd

      - name: Start Docker daemon manually
        run: |
          nohup dockerd > /dev/null 2>&1 &
          sleep 15
          docker info

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front-end
          file: front-end/my-vue-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/frontend-git:latest

  deploy:
    name: Deploy to Kubernetes
    needs: build  # Só roda após a conclusão do build
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          kubectl config set-context kind-fatec-cluster --cluster=kind-fatec-cluster --user=kind-fatec-cluster

      - name: Check connection with Kubernetes
        run: |
          kubectl get pods -A
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Deploy Frontend with Helm
        run: |
          cd front-end/kubernetes
          helm upgrade --install frontend . --values values.yaml
