name: CI/CD - Build and Deploy Frontend to GCP Cluster

# Disparo manual ativado, eventos automáticos desativados
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          ls -la
          pwd

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to GCP Artifact Registry
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build and push Frontend Docker image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: ./front-end/my-vue-app
          file: front-end/my-vue-app/Dockerfile
          push: true
          tags: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/fatec-frontend:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install kubectl
        run: gcloud components install kubectl

      - name: Get GKE cluster credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GCP_K8S_CLUSTER_NAME }}
          location: ${{ secrets.GCP_K8S_ZONE }}

      - name: Authenticate with Kubernetes
        run: |
          kubectl config get-contexts
          kubectl cluster-info
          kubectl get pods -A

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Deploy Frontend with Helm
        run: |
          cd front-end/kubernetes
          helm upgrade --install frontend . --values values.yaml -n production
