name: Build and Deploy backend_omdb app

# Teste Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Build-and-deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Configurar kubectl for kind
      - name: Configure kubectl
        run: |
          kubectl config set-context fatec-cluster --cluster=fatec-cluster --user=fatec-cluster

      # Verifica conexão kubernetes
      - name: Check connection with Kubernetes
        run: |
          kubectl get pods -A
          kubectl get nodes

      # Instalar Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      # Realizar login no Docker registry 
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # acessa a pasta backend_omdd, gerar uma imagem com o Dockerfile e armazenar em um registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend_omdb
          file: backend_omdb/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/backend_omdb:latest

      # Deploy com Helm
      - name: Deploy with Helm
        run: |
          cd backend_omdb/kubernetes
          ls
          pwd
          helm upgrade --install backend-omdb . --set image.repository=${{ secrets.DOCKER_REGISTRY }}/backend_omdb --set image.tag=latest
          